version: '2.1'

services:
  nodejs_typescript_template:
    image: nodejs_typescript_template
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js